import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LANGUAGE_KEY = "damulink-language";

export const LANGUAGES = [
  {
    value: "en",
    label: "English",
    nativeLabel: "English",
    description: "Use English across DamuLink",
  },
  {
    value: "sw",
    label: "Swahili",
    nativeLabel: "Kiswahili",
    description: "Tumia Kiswahili kwenye DamuLink",
  },
];

const translations = {
  en: {
    "access.open": "Open accessibility settings",
    "access.dialog": "Accessibility settings",
    "access.display": "Display",
    "access.language": "Language",
    "access.colorMode": "Color mode",
    "access.languageMode": "Site language",
    "access.default.label": "Default",
    "access.default.description": "Original warm DamuLink colors",
    "access.dark.label": "Dark",
    "access.dark.description": "Lower glare with preserved ruby accents",
    "access.contrast.label": "High contrast",
    "access.contrast.description": "Sharper edges and stronger color separation",
    "access.english.description": "Use English across DamuLink",
    "access.swahili.description": "Tumia Kiswahili kwenye DamuLink",

    "common.brand": "DamuLink",
    "common.loading": "Loading...",
    "common.logIn": "Log in",
    "common.logout": "Log out",
    "common.becomeDonor": "Become a donor",
    "common.registerDonor": "Register as a donor",
    "common.haveAccount": "I have an account",
    "common.continue": "Continue",
    "common.saving": "Saving...",
    "common.creatingAccount": "Creating account...",
    "common.verifying": "Verifying...",
    "common.backDashboard": "Back to dashboard",

    "landing.choice.title": "How are you joining DamuLink?",
    "landing.choice.donorLabel": "I'm a donor",
    "landing.choice.donorBody": "Register your blood or organ donation, get matched with hospitals nearby.",
    "landing.choice.hospitalLabel": "I'm a hospital",
    "landing.choice.hospitalBody": "Search verified donors, manage requests, and access the national network.",
    "landing.choice.donorLogin": "Donor login",
    "landing.choice.hospitalLogin": "Hospital login",

    "hospital.login.eyebrow": "Clinical access",
    "hospital.login.sideHeading": "The donor you need might be 4km away.",
    "hospital.login.sideBody": "Search the national donor network by blood type, organ, and distance.",
    "hospital.login.title": "Hospital login",
    "hospital.login.body": "Enter your facility's registered email and password.",
    "hospital.login.error": "Couldn't log you in. Check your details and try again.",
    "hospital.login.new": "New facility?",
    "hospital.login.register": "Register your hospital",
    "hospital.login.donorInstead": "Looking for the donor app?",
    "hospital.login.donorLink": "Go to donor login",

    "landing.eyebrow": "Kenya's donor network",
    "landing.title.line1": "One drop",
    "landing.title.line2": "reaches",
    "landing.title.accent": "far",
    "landing.body":
      "DamuLink connects verified blood and organ donors with hospitals across the country - so when someone needs help, the right person isn't far away.",
    "landing.stat.types.value": "8",
    "landing.stat.types.label": "Blood types matched",
    "landing.stat.alerts.value": "24/7",
    "landing.stat.alerts.label": "Urgent request alerts",
    "landing.stat.ussd.value": "USSD",
    "landing.stat.ussd.label": "Works without internet",

    "footer.brand": "DamuLink",
"footer.tagline": "Every drop counts.",
"footer.copyright": "© 2025 DamuLink. All rights reserved.",

"footer.company": "Company",
"footer.home": "Home",
"footer.signUp": "Sign up",
"footer.login": "Login",
"footer.credits": "Credits",

"footer.donors": "Donors",
"footer.dashboard": "Dashboard",
"footer.contact": "Contact Requests",
"footer.history": "Donation History",
"footer.badges": "Badges",

"footer.hospitals": "Hospitals",
"footer.hospitalLogin": "Hospital Login",
"footer.hospitalRegister": "Register Hospital",
"footer.findHospital": "Find Hospitals",

"footer.address": "Nairobi, Kenya",


    "auth.login.eyebrow": "Welcome back",
    "auth.login.sideHeading": "Your blood type is needed somewhere, right now.",
    "auth.login.sideBody": "Log in to check your credits, badges, and the donations that got you here.",
    "auth.login.title": "Log in",
    "auth.login.body": "Enter the phone number and password you registered with.",
    "auth.login.error": "Couldn't log you in. Check your details and try again.",
    "auth.login.submitting": "Logging in...",
    "auth.login.new": "New to DamuLink?",
    "auth.login.register": "Register as a donor",

    "auth.signup.step0.eyebrow": "Two minutes, start to finish",
    "auth.signup.step0.heading": "Your details stay yours until you say go.",
    "auth.signup.step0.body":
      "Full contact details are only shared with a hospital after you personally accept a request.",
    "auth.signup.step1.eyebrow": "Almost there",
    "auth.signup.step1.heading": "One code, sent straight to your phone.",
    "auth.signup.step1.body": "This confirms the number hospitals will reach you on when it matters.",
    "auth.signup.step2.eyebrow": "Welcome",
    "auth.signup.step2.heading": "You're part of the network now.",
    "auth.signup.step2.body": "Next, your blood type and location - that's what makes the match.",
    "auth.signup.title": "Create your account",
    "auth.signup.body": "You'll verify your phone number next.",
    "auth.signup.error": "Registration failed. Please try again.",
    "auth.signup.already": "Already have an account?",
    "auth.signup.verifyTitle": "Verify your phone",
    "auth.signup.verifyBody": "We sent a code to {phone}. Enter it below.",
    "auth.signup.verifyFallback": "your phone",
    "auth.signup.verifyError": "That code didn't work. Check it and try again.",
    "auth.signup.resendError": "Couldn't resend the code. Try again shortly.",
    "auth.signup.verifyAction": "Verify and continue",
    "auth.signup.resend": "Resend code",
    "auth.signup.doneTitle": "You're verified",
    "auth.signup.doneBody":
      "Log in with the password you just set, then we'll get your blood type and location so hospitals near you can find a match.",
    "auth.signup.doneAction": "Log in to continue",

    "field.fullName": "Full legal name",
    "field.phone": "Phone number",
    "field.emailOptional": "Email (optional)",
    "field.nationalId": "National ID number",
    "field.birthDate": "Date of birth",
    "field.password": "Password",
    "field.verificationCode": "Verification code",

    "profile.lastStep": "Last step",
    "profile.title": "Your donor profile",
    "profile.body":
      "This is what hospitals see when they search for a match. Your exact location and full contact details stay private until you say yes.",
    "profile.error": "Couldn't save your profile. Please try again.",
    "profile.bloodType": "Blood type",
    "profile.donorQuestion": "What would you like to donate?",
    "profile.organsQuestion": "Which organs would you pledge?",
    "profile.location": "Where to find you",
    "profile.county": "County",
    "profile.town": "Town",
    "profile.contactPreference": "Preferred contact method",
    "profile.insurance": "Insurance provider (optional)",
    "profile.insurancePlaceholder": "e.g. SHA, Jubilee Health, AAR",
    "profile.save": "Save profile and continue",
    "profile.donor.blood": "Blood only",
    "profile.donor.organ": "Organ only",
    "profile.donor.both": "Both",
    "profile.organ.kidney": "kidney",
    "profile.organ.liver": "liver",
    "profile.organ.cornea": "cornea",
    "profile.organ.heart": "heart",
    "profile.organ.bone marrow": "bone marrow",
    "profile.contact.call": "Call",
    "profile.contact.sms": "SMS",
    "profile.contact.whatsapp": "WhatsApp",

    "dashboard.loadError": "Couldn't load everything just now. Pull to refresh in a bit.",
    "dashboard.welcomeNamed": "Welcome back, {name}",
    "dashboard.welcome": "Welcome back",
    "dashboard.bloodTypeCopy": "Your blood type{bloodType} could be exactly what someone needs today.",
    "dashboard.bloodTypeValue": " - {bloodType}",
    "dashboard.oneRequest": "A hospital is waiting on your response",
    "dashboard.manyRequests": "{count} hospitals are waiting on your response",
    "dashboard.reviewRequest": "Review the request before it expires",
    "dashboard.view": "View ->",
    "dashboard.credits": "Credit balance",
    "dashboard.redeemable": "Redeemable at any partnered hospital",
    "dashboard.availability": "Availability",
    "dashboard.available": "Hospitals can find and contact you",
    "dashboard.hidden": "You're hidden from new requests",
    "dashboard.badgesEarned": "Badges earned",
    "dashboard.latestBadge": "Latest: {badge}",
    "dashboard.firstBadge": "Donate to earn your first",
    "dashboard.badgesTitle": "Your badges",
    "dashboard.noBadgesTitle": "No badges yet",
    "dashboard.noBadgesBody": "Your first donation unlocks Rookie Lifesaver. It's closer than you think.",
    "dashboard.historyTitle": "Donation history",
    "dashboard.noHistoryTitle": "No donations recorded yet",
    "dashboard.noHistoryBody":
      "Once a hospital confirms your donation, it shows up here with the credits you earned.",
    "dashboard.earned": "Earned {date}",

    "requests.title": "Hospital requests",
    "requests.body":
      "When a verified hospital wants to reach you, it shows up here first. Nothing is shared until you say yes.",
    "requests.loadError": "Couldn't load your requests right now.",
    "requests.actionError": "That didn't go through. Please try again.",
    "requests.loading": "Loading...",
    "requests.needsResponse": "Needs your response",
    "requests.past": "Past requests",
    "requests.accept": "Accept and share contact",
    "requests.busy": "...",
    "requests.decline": "Decline",
    "requests.emptyTitle": "No requests yet",
    "requests.emptyBody":
      "When a hospital near you needs your blood type, you'll see it here before anything else happens.",
    "requests.status.pending": "Awaiting your response",
    "requests.status.accepted": "Accepted",
    "requests.status.declined": "Declined",
    "requests.status.expired": "Expired",

    "redeem.title": "Redeem your credits",
    "redeem.body": "Use your credits as partial payment at any partnered hospital — for outpatient bills, lab tests, or pharmacy.",
    "redeem.balanceLabel": "Available balance",
    "redeem.hospitalLabel": "Hospital name",
    "redeem.hospitalPlaceholder": "e.g. Nairobi West Hospital",
    "redeem.amountLabel": "Credits to redeem",
    "redeem.amountHint": "100 credits ≈ KES 100",
    "redeem.submit": "Redeem credits",
    "redeem.submitting": "Redeeming...",
    "redeem.error": "Couldn't redeem your credits. Please try again.",
    "redeem.insufficientError": "You don't have enough credits for that amount.",
    "redeem.successTitle": "Credits redeemed",
    "redeem.successBody": "{amount} credits were redeemed at {hospital}. Your new balance is {balance}.",
    "redeem.doneAction": "Back to dashboard",
    "redeem.redeemAnother": "Redeem again",
    "redeem.back": "Back",
    "redeem.ledgerTitle": "Recent activity",
    "redeem.ledgerEmpty": "No credit activity yet.",
    "redeem.earnType": "Earned",
    "redeem.redeemType": "Redeemed",

    "leaderboard.title": "Community leaderboard",
    "leaderboard.body": "See how DamuLink donors are showing up for each other this season.",
    "leaderboard.loadError": "Couldn't load the leaderboard right now.",
    "leaderboard.you": "You",
    "leaderboard.rank": "Rank",
    "leaderboard.donor": "Donor",
    "leaderboard.credits": "Credits",
    "leaderboard.empty": "No leaderboard data yet — be the first to show up.",
    "leaderboard.backDashboard": "Back to dashboard",

    "nav.account": "Your account",
    "nav.profile": "Profile & settings",
    "nav.donations": "Donation history",
    "nav.verification": "Identity verification",
    "nav.thirdParty": "Third-party data access",
    "nav.about": "About DamuLink",

    "about.donor.eyebrow": "Why DamuLink exists",
    "about.donor.title": "Every drop has a name behind it",
    "about.donor.intro": "Somewhere in Kenya right now, a hospital is searching for a blood type that matches yours. DamuLink exists to close that distance — quickly, safely, and with you fully in control of who gets to reach you.",

    "about.donor.howTitle": "How a donation actually works",
    "about.donor.step1.title": "Register and verify",
    "about.donor.step1.body": "Tell us your blood type, location, and how you'd like to be reached. Your ID is verified so hospitals can trust who they're contacting.",
    "about.donor.step2.title": "Hospitals search, you stay hidden",
    "about.donor.step2.body": "A hospital searching for your blood type only sees your first name, distance, and donation history — never your phone number or address.",
    "about.donor.step3.title": "You get the final say",
    "about.donor.step3.body": "When a hospital wants to reach you, you get an SMS first. Reply yes and they get your contact details. Reply no, or don't reply, and nothing is shared.",
    "about.donor.step4.title": "Donate and earn credits",
    "about.donor.step4.body": "Once a hospital confirms your donation, you earn health credits — redeemable at any partnered facility for outpatient bills, lab tests, or pharmacy costs.",

    "about.donor.impactTitle": "What your credits and badges mean",
    "about.donor.impactBody": "100 credits ≈ KES 100 in real value at any partnered hospital. Badges like Rookie Lifesaver and Damu Legend track your journey — purely for recognition, never required.",

    "about.donor.foundersTitle": "The people behind DamuLink",
    "about.donor.foundersNote": "Placeholder profiles — real founder details coming soon.",
    "about.donor.founder1.name": "Founder Name",
    "about.donor.founder1.role": "Founder & CEO",
    "about.donor.founder2.name": "Founder Name",
    "about.donor.founder2.role": "Co-Founder & CTO",
    "about.donor.founder3.name": "Founder Name",
    "about.donor.founder3.role": "Head of Medical Partnerships",

    "about.donor.partnersTitle": "Partners powering the network",
    "about.donor.partnersNote": "Placeholder partners — confirmed integrations coming soon.",
    "about.donor.partner1": "Africa's Talking — SMS & USSD",
    "about.donor.partner2": "M-Pesa Daraja — Payments",
    "about.donor.partner3": "Partner Hospital Network",
    "about.donor.partner4": "Kenya National Blood Transfusion Service",

    "about.donor.backDashboard": "Back to dashboard",

    "about.hospital.eyebrow": "For verified medical facilities",
    "about.hospital.title": "The donor you need might be 4km away",
    "about.hospital.intro": "DamuLink is the national donor search network — built so your facility can find a matching, willing donor in minutes instead of hours, without ever holding raw donor data you don't need.",

    "about.hospital.howTitle": "How search and contact work",
    "about.hospital.step1.title": "Search by type, organ, and radius",
    "about.hospital.step1.body": "Filter by blood type or organ need, distance from your facility, and availability. Results show distance and donation history — full contact stays private.",
    "about.hospital.step2.title": "Initiate a contact request",
    "about.hospital.step2.body": "Every request is logged with timestamp and reason. The donor is notified by SMS and chooses whether to share their details.",
    "about.hospital.step3.title": "Confirm the donation",
    "about.hospital.step3.body": "Once the donation happens, confirm it in your dashboard — this is what credits the donor and keeps the network's records accurate.",
    "about.hospital.step4.title": "Track it all in your audit log",
    "about.hospital.step4.body": "Every search and contact request your staff make is logged and reviewable, in line with the Kenya Data Protection Act.",

    "about.hospital.tiersTitle": "Subscription tiers",
    "about.hospital.tier1.name": "Starter",
    "about.hospital.tier1.price": "KES 5,000/mo",
    "about.hospital.tier1.detail": "100 searches/month, basic search, SMS contact",
    "about.hospital.tier2.name": "Professional",
    "about.hospital.tier2.price": "KES 15,000/mo",
    "about.hospital.tier2.detail": "500 searches/month, organ donor access, analytics",
    "about.hospital.tier3.name": "Enterprise",
    "about.hospital.tier3.price": "KES 40,000/mo",
    "about.hospital.tier3.detail": "Unlimited searches, API access, dedicated support",
    "about.hospital.tier4.name": "Public Hospital",
    "about.hospital.tier4.price": "KES 1,500/mo",
    "about.hospital.tier4.detail": "Subsidized rate for government-registered facilities",

    "about.hospital.complianceTitle": "Data handling you can rely on",
    "about.hospital.complianceBody": "No raw donor data leaves the platform without consent. Your facility never sees a donor's exact address or ID documents — only what's needed to make contact, after they say yes.",

    "about.hospital.foundersTitle": "The people behind DamuLink",
    "about.hospital.partnersTitle": "Partners powering the network",
    "about.hospital.partnersNote": "Placeholder partners — confirmed integrations coming soon.",

    "about.hospital.backDashboard": "Back to dashboard",
  },
  sw: {
    "access.open": "Fungua mipangilio ya ufikikaji",
    "access.dialog": "Mipangilio ya ufikikaji",
    "access.display": "Mwonekano",
    "access.language": "Lugha",
    "access.colorMode": "Mtindo wa rangi",
    "access.languageMode": "Lugha ya tovuti",
    "access.default.label": "Chaguo msingi",
    "access.default.description": "Rangi asili za joto za DamuLink",
    "access.dark.label": "Hali ya giza",
    "access.dark.description": "Mwanga mdogo mkali huku rangi nyekundu zikibaki",
    "access.contrast.label": "Utofautishaji mkubwa",
    "access.contrast.description": "Mipaka iliyo wazi na rangi zinazotofautiana zaidi",
    "access.english.description": "Tumia Kiingereza kwenye DamuLink",
    "access.swahili.description": "Tumia Kiswahili kwenye DamuLink",

    "common.brand": "DamuLink",
    "common.loading": "Inapakia...",
    "common.logIn": "Ingia",
    "common.logout": "Toka",
    "common.becomeDonor": "Kuwa mfadhili",
    "common.registerDonor": "Jisajili kama mfadhili",
    "common.haveAccount": "Tayari nina akaunti",
    "common.continue": "Endelea",
    "common.saving": "Inahifadhi...",
    "common.creatingAccount": "Inaunda akaunti...",
    "common.verifying": "Inathibitisha...",
    "common.backDashboard": "Rudi kwenye dashibodi",

    "landing.choice.title": "Unajiunga na DamuLink kama nani?",
    "landing.choice.donorLabel": "Mimi ni mfadhili",
    "landing.choice.donorBody": "Jisajili kuchangia damu au kiungo, ulinganishwe na hospitali zilizo karibu.",
    "landing.choice.hospitalLabel": "Mimi ni hospitali",
    "landing.choice.hospitalBody": "Tafuta wafadhili waliothibitishwa, simamia maombi, na fikia mtandao wa kitaifa.",
    "landing.choice.donorLogin": "Ingia kama mfadhili",
    "landing.choice.hospitalLogin": "Ingia kama hospitali",

    "hospital.login.eyebrow": "Ufikiaji wa kliniki",
    "hospital.login.sideHeading": "Mfadhili unayehitaji huenda yupo kilomita 4 tu.",
    "hospital.login.sideBody": "Tafuta mtandao wa kitaifa wa wafadhili kwa aina ya damu, kiungo, na umbali.",
    "hospital.login.title": "Ingia kama hospitali",
    "hospital.login.body": "Weka barua pepe na nenosiri lililosajiliwa la kituo chako.",
    "hospital.login.error": "Imeshindikana kukuingiza. Kagua maelezo yako kisha ujaribu tena.",
    "hospital.login.new": "Kituo kipya?",
    "hospital.login.register": "Sajili hospitali yako",
    "hospital.login.donorInstead": "Unatafuta programu ya mfadhili?",
    "hospital.login.donorLink": "Nenda kwa kuingia kama mfadhili",

    "landing.eyebrow": "Mtandao wa wafadhili Kenya",
    "landing.title.line1": "Tone moja",
    "landing.title.line2": "hufika",
    "landing.title.accent": "mbali",
    "landing.body":
      "DamuLink huwaunganisha wafadhili wa damu na viungo waliothibitishwa na hospitali nchini kote - ili mtu anapohitaji msaada, mfadhili anayefaa asiwe mbali.",
    "landing.stat.types.value": "8",
    "landing.stat.types.label": "Aina za damu zinazolinganishwa",
    "landing.stat.alerts.value": "24/7",
    "landing.stat.alerts.label": "Arifa za dharura za maombi",
    "landing.stat.ussd.value": "USSD",
    "landing.stat.ussd.label": "Hufanya kazi bila intaneti",

    "auth.login.eyebrow": "Karibu tena",
    "auth.login.sideHeading": "Aina yako ya damu inahitajika mahali fulani sasa hivi.",
    "auth.login.sideBody": "Ingia kuona salio lako, beji zako, na michango iliyokufikisha hapa.",
    "auth.login.title": "Ingia",
    "auth.login.body": "Weka nambari ya simu na nenosiri ulilotumia kujisajili.",
    "auth.login.error": "Imeshindikana kukuingiza. Kagua maelezo yako kisha ujaribu tena.",
    "auth.login.submitting": "Inaingia...",
    "auth.login.new": "Mgeni kwenye DamuLink?",
    "auth.login.register": "Jisajili kama mfadhili",

    "auth.signup.step0.eyebrow": "Dakika mbili, mwanzo hadi mwisho",
    "auth.signup.step0.heading": "Maelezo yako yanabaki yako mpaka utoe ruhusa.",
    "auth.signup.step0.body":
      "Maelezo kamili ya mawasiliano hushirikiwa na hospitali tu baada ya wewe kukubali ombi.",
    "auth.signup.step1.eyebrow": "Uko karibu kumaliza",
    "auth.signup.step1.heading": "Msimbo mmoja, umetumwa moja kwa moja kwenye simu yako.",
    "auth.signup.step1.body": "Hii huthibitisha nambari ambayo hospitali zitakutumia zikiwa na uhitaji.",
    "auth.signup.step2.eyebrow": "Karibu",
    "auth.signup.step2.heading": "Sasa wewe ni sehemu ya mtandao huu.",
    "auth.signup.step2.body": "Kinachofuata ni aina yako ya damu na eneo lako - hivyo ndivyo ulinganishaji hufanyika.",
    "auth.signup.title": "Fungua akaunti yako",
    "auth.signup.body": "Utathibitisha nambari yako ya simu hatua inayofuata.",
    "auth.signup.error": "Usajili umeshindikana. Tafadhali jaribu tena.",
    "auth.signup.already": "Tayari una akaunti?",
    "auth.signup.verifyTitle": "Thibitisha simu yako",
    "auth.signup.verifyBody": "Tumetuma msimbo kwa {phone}. Uweke hapa chini.",
    "auth.signup.verifyFallback": "simu yako",
    "auth.signup.verifyError": "Msimbo huo haujafanya kazi. Ukague kisha ujaribu tena.",
    "auth.signup.resendError": "Imeshindikana kutuma msimbo tena. Jaribu tena baada ya muda mfupi.",
    "auth.signup.verifyAction": "Thibitisha na uendelee",
    "auth.signup.resend": "Tuma msimbo tena",
    "auth.signup.doneTitle": "Umethibitishwa",
    "auth.signup.doneBody":
      "Ingia kwa nenosiri uliloweka, kisha tutachukua aina yako ya damu na eneo lako ili hospitali zilizo karibu zikupate zikihitaji ulinganishaji.",
    "auth.signup.doneAction": "Ingia ili uendelee",

    "field.fullName": "Jina kamili la kisheria",
    "field.phone": "Nambari ya simu",
    "field.emailOptional": "Barua pepe (si lazima)",
    "field.nationalId": "Nambari ya kitambulisho",
    "field.birthDate": "Tarehe ya kuzaliwa",
    "field.password": "Nenosiri",
    "field.verificationCode": "Msimbo wa uthibitishaji",

    "profile.lastStep": "Hatua ya mwisho",
    "profile.title": "Wasifu wako wa ufadhili",
    "profile.body":
      "Haya ndiyo hospitali huona zinapotafuta ulinganishaji. Eneo lako halisi na maelezo kamili ya mawasiliano hubaki binafsi hadi useme ndiyo.",
    "profile.error": "Imeshindikana kuhifadhi wasifu wako. Tafadhali jaribu tena.",
    "profile.bloodType": "Aina ya damu",
    "profile.donorQuestion": "Ungependa kuchangia nini?",
    "profile.organsQuestion": "Ni viungo gani ungeahidi kuchangia?",
    "profile.location": "Mahali unapopatikana",
    "profile.county": "Kaunti",
    "profile.town": "Mji",
    "profile.contactPreference": "Njia unayopendelea ya mawasiliano",
    "profile.insurance": "Mtoa bima (si lazima)",
    "profile.insurancePlaceholder": "mf. SHA, Jubilee Health, AAR",
    "profile.save": "Hifadhi wasifu na uendelee",
    "profile.donor.blood": "Damu pekee",
    "profile.donor.organ": "Viungo pekee",
    "profile.donor.both": "Vyote",
    "profile.organ.kidney": "figo",
    "profile.organ.liver": "ini",
    "profile.organ.cornea": "konea",
    "profile.organ.heart": "moyo",
    "profile.organ.bone marrow": "uboho",
    "profile.contact.call": "Piga simu",
    "profile.contact.sms": "SMS",
    "profile.contact.whatsapp": "WhatsApp",

    "dashboard.loadError": "Imeshindikana kupakia kila kitu kwa sasa. Jaribu kuonyesha upya baada ya muda.",
    "dashboard.welcomeNamed": "Karibu tena, {name}",
    "dashboard.welcome": "Karibu tena",
    "dashboard.bloodTypeCopy": "Aina yako ya damu{bloodType} inaweza kuwa kile mtu anahitaji leo.",
    "dashboard.bloodTypeValue": " - {bloodType}",
    "dashboard.oneRequest": "Hospitali inasubiri jibu lako",
    "dashboard.manyRequests": "Hospitali {count} zinasubiri jibu lako",
    "dashboard.reviewRequest": "Kagua ombi kabla muda wake haujaisha",
    "dashboard.view": "Tazama ->",
    "dashboard.credits": "Salio la pointi",
    "dashboard.redeemable": "Zinaweza kutumika katika hospitali yoyote mshirika",
    "dashboard.availability": "Upatikanaji",
    "dashboard.available": "Hospitali zinaweza kukupata na kuwasiliana nawe",
    "dashboard.hidden": "Umefichwa dhidi ya maombi mapya",
    "dashboard.badgesEarned": "Beji ulizopata",
    "dashboard.latestBadge": "Ya hivi karibuni: {badge}",
    "dashboard.firstBadge": "Changia ili upate beji yako ya kwanza",
    "dashboard.badgesTitle": "Beji zako",
    "dashboard.noBadgesTitle": "Bado hakuna beji",
    "dashboard.noBadgesBody": "Mchango wako wa kwanza hufungua beji ya Rookie Lifesaver. Uko karibu kuliko unavyodhani.",
    "dashboard.historyTitle": "Historia ya michango",
    "dashboard.noHistoryTitle": "Bado hakuna michango iliyorekodiwa",
    "dashboard.noHistoryBody":
      "Hospitali ikithibitisha mchango wako, utaonekana hapa pamoja na pointi ulizopata.",
    "dashboard.earned": "Ilipatikana {date}",

    "requests.title": "Maombi ya hospitali",
    "requests.body":
      "Hospitali iliyothibitishwa ikitaka kuwasiliana nawe, itaonekana hapa kwanza. Hakuna kinachoshirikiwa hadi useme ndiyo.",
    "requests.loadError": "Imeshindikana kupakia maombi yako kwa sasa.",
    "requests.actionError": "Hatua hiyo haijakamilika. Tafadhali jaribu tena.",
    "requests.loading": "Inapakia...",
    "requests.needsResponse": "Yanahitaji jibu lako",
    "requests.past": "Maombi yaliyopita",
    "requests.accept": "Kubali na ushiriki mawasiliano",
    "requests.busy": "...",
    "requests.decline": "Kataa",
    "requests.emptyTitle": "Bado hakuna maombi",
    "requests.emptyBody":
      "Hospitali iliyo karibu ikihitaji aina yako ya damu, utaiona hapa kabla jambo lingine lolote halijafanyika.",
    "requests.status.pending": "Inasubiri jibu lako",
    "requests.status.accepted": "Imekubaliwa",
    "requests.status.declined": "Imekataliwa",
    "requests.status.expired": "Muda umeisha",

    "redeem.title": "Tumia pointi zako",
    "redeem.body": "Tumia pointi zako kama malipo ya sehemu katika hospitali yoyote mshirika — kwa bili za nje, vipimo vya maabara, au dawa.",
    "redeem.balanceLabel": "Salio linalopatikana",
    "redeem.hospitalLabel": "Jina la hospitali",
    "redeem.hospitalPlaceholder": "mf. Nairobi West Hospital",
    "redeem.amountLabel": "Pointi za kutumia",
    "redeem.amountHint": "Pointi 100 ≈ KES 100",
    "redeem.submit": "Tumia pointi",
    "redeem.submitting": "Inatumia...",
    "redeem.error": "Imeshindikana kutumia pointi zako. Tafadhali jaribu tena.",
    "redeem.insufficientError": "Huna pointi za kutosha kwa kiasi hicho.",
    "redeem.successTitle": "Pointi zimetumika",
    "redeem.successBody": "Pointi {amount} zimetumika katika {hospital}. Salio lako jipya ni {balance}.",
    "redeem.doneAction": "Rudi kwenye dashibodi",
    "redeem.redeemAnother": "Tumia tena",
    "redeem.back": "Rudi",
    "redeem.ledgerTitle": "Shughuli za hivi karibuni",
    "redeem.ledgerEmpty": "Bado hakuna shughuli za pointi.",
    "redeem.earnType": "Ilipatikana",
    "redeem.redeemType": "Ilitumika",

    "leaderboard.title": "Ubao wa jamii",
    "leaderboard.body": "Tazama jinsi wafadhili wa DamuLink wanavyojitokeza kwa ajili ya mtu mwenzao msimu huu.",
    "leaderboard.loadError": "Imeshindikana kupakia ubao wa jamii kwa sasa.",
    "leaderboard.you": "Wewe",
    "leaderboard.rank": "Nafasi",
    "leaderboard.donor": "Mfadhili",
    "leaderboard.credits": "Pointi",
    "leaderboard.empty": "Bado hakuna data ya ubao wa jamii — kuwa wa kwanza kujitokeza.",
    "leaderboard.backDashboard": "Rudi kwenye dashibodi",

    "nav.account": "Akaunti yako",
    "nav.profile": "Wasifu na mipangilio",
    "nav.donations": "Historia ya michango",
    "nav.verification": "Uthibitishaji wa utambulisho",
    "nav.thirdParty": "Ufikiaji wa data wa wahusika wengine",
    "nav.about": "Kuhusu DamuLink",

    "about.donor.eyebrow": "Kwa nini DamuLink ipo",
    "about.donor.title": "Kila tone lina jina nyuma yake",
    "about.donor.intro": "Mahali fulani Kenya sasa hivi, hospitali inatafuta aina ya damu inayofanana na yako. DamuLink ipo kufunga pengo hilo — kwa kasi, kwa usalama, na wewe ukiwa na uongozi kamili wa nani anayeweza kukufikia.",

    "about.donor.howTitle": "Jinsi mchango unavyofanya kazi",
    "about.donor.step1.title": "Jisajili na uthibitishwe",
    "about.donor.step1.body": "Tuambie aina yako ya damu, eneo lako, na jinsi unavyopendelea kufikiwa. Kitambulisho chako huthibitishwa ili hospitali ziweze kumwamini wanayemwasiliana naye.",
    "about.donor.step2.title": "Hospitali hutafuta, wewe hubaki umefichwa",
    "about.donor.step2.body": "Hospitali inayotafuta aina yako ya damu huona tu jina lako la mwanzo, umbali, na historia ya michango — kamwe si nambari yako ya simu au anwani.",
    "about.donor.step3.title": "Wewe ndiye unayetoa uamuzi wa mwisho",
    "about.donor.step3.body": "Hospitali inapotaka kukufikia, utapata SMS kwanza. Jibu ndiyo na watapata maelezo yako ya mawasiliano. Jibu hapana, au usijibu, na hakuna kitakachoshirikiwa.",
    "about.donor.step4.title": "Changia na upate pointi",
    "about.donor.step4.body": "Hospitali ikithibitisha mchango wako, hupata pointi za afya — zinazoweza kutumika katika kituo chochote mshirika kwa bili za nje, vipimo vya maabara, au dawa.",

    "about.donor.impactTitle": "Maana ya pointi na beji zako",
    "about.donor.impactBody": "Pointi 100 ≈ thamani halisi ya KES 100 katika hospitali yoyote mshirika. Beji kama Rookie Lifesaver na Damu Legend hufuatilia safari yako — kwa ajili ya kutambuliwa tu, kamwe si lazima.",

    "about.donor.foundersTitle": "Watu walio nyuma ya DamuLink",
    "about.donor.foundersNote": "Wasifu wa muda — maelezo halisi ya waanzilishi yanakuja hivi karibuni.",
    "about.donor.founder1.name": "Jina la Mwanzilishi",
    "about.donor.founder1.role": "Mwanzilishi na Afisa Mkuu",
    "about.donor.founder2.name": "Jina la Mwanzilishi",
    "about.donor.founder2.role": "Mwanzilishi Mwenza na Afisa wa Teknolojia",
    "about.donor.founder3.name": "Jina la Mwanzilishi",
    "about.donor.founder3.role": "Mkuu wa Ushirikiano wa Kimatibabu",

    "about.donor.partnersTitle": "Washirika wanaoendesha mtandao",
    "about.donor.partnersNote": "Washirika wa muda — ushirikiano uliothibitishwa unakuja hivi karibuni.",
    "about.donor.partner1": "Africa's Talking — SMS na USSD",
    "about.donor.partner2": "M-Pesa Daraja — Malipo",
    "about.donor.partner3": "Mtandao wa Hospitali Mshirika",
    "about.donor.partner4": "Huduma ya Kitaifa ya Uhamisho wa Damu Kenya",

    "about.donor.backDashboard": "Rudi kwenye dashibodi",

    "about.hospital.eyebrow": "Kwa vituo vya matibabu vilivyothibitishwa",
    "about.hospital.title": "Mfadhili unayehitaji huenda yupo kilomita 4 tu",
    "about.hospital.intro": "DamuLink ni mtandao wa kitaifa wa kutafuta wafadhili — uliojengwa ili kituo chako kipate mfadhili anayefanana na anayetaka kuchangia ndani ya dakika badala ya masaa, bila kushikilia data ghafi ya wafadhili usiyoihitaji.",

    "about.hospital.howTitle": "Jinsi utafutaji na mawasiliano hufanya kazi",
    "about.hospital.step1.title": "Tafuta kwa aina, kiungo, na umbali",
    "about.hospital.step1.body": "Chuja kwa aina ya damu au uhitaji wa kiungo, umbali kutoka kituo chako, na upatikanaji. Matokeo huonyesha umbali na historia ya michango — mawasiliano kamili hubaki ya faragha.",
    "about.hospital.step2.title": "Anzisha ombi la mawasiliano",
    "about.hospital.step2.body": "Kila ombi hurekodiwa na muda na sababu. Mfadhili hupokea arifa kupitia SMS na huchagua kama atashiriki maelezo yake.",
    "about.hospital.step3.title": "Thibitisha mchango",
    "about.hospital.step3.body": "Mchango ukifanyika, uthibitishe kwenye dashibodi yako — hii ndiyo humpa mfadhili pointi na kuhakikisha rekodi za mtandao ni sahihi.",
    "about.hospital.step4.title": "Fuatilia kila kitu kwenye rekodi yako ya ukaguzi",
    "about.hospital.step4.body": "Kila utafutaji na ombi la mawasiliano linalofanywa na wafanyakazi wako hurekodiwa na huweza kukaguliwa, kwa mujibu wa Sheria ya Ulinzi wa Data Kenya.",

    "about.hospital.tiersTitle": "Viwango vya usajili",
    "about.hospital.tier1.name": "Mwanzo",
    "about.hospital.tier1.price": "KES 5,000/mwezi",
    "about.hospital.tier1.detail": "Utafutaji 100/mwezi, utafutaji wa kawaida, mawasiliano ya SMS",
    "about.hospital.tier2.name": "Kitaalamu",
    "about.hospital.tier2.price": "KES 15,000/mwezi",
    "about.hospital.tier2.detail": "Utafutaji 500/mwezi, ufikiaji wa wafadhili wa viungo, uchanganuzi",
    "about.hospital.tier3.name": "Biashara Kubwa",
    "about.hospital.tier3.price": "KES 40,000/mwezi",
    "about.hospital.tier3.detail": "Utafutaji usio na kikomo, ufikiaji wa API, msaada maalum",
    "about.hospital.tier4.name": "Hospitali ya Umma",
    "about.hospital.tier4.price": "KES 1,500/mwezi",
    "about.hospital.tier4.detail": "Kiwango cha ruzuku kwa vituo vilivyosajiliwa na serikali",

    "about.hospital.complianceTitle": "Uongozi wa data unaoweza kutegemewa",
    "about.hospital.complianceBody": "Hakuna data ghafi ya mfadhili inayoondoka kwenye jukwaa bila ridhaa. Kituo chako kamwe hakioni anwani halisi ya mfadhili au hati za kitambulisho — tu kile kinachohitajika kuwasiliana, baada ya kusema ndiyo.",

    "about.hospital.foundersTitle": "Watu walio nyuma ya DamuLink",
    "about.hospital.partnersTitle": "Washirika wanaoendesha mtandao",
    "about.hospital.partnersNote": "Washirika wa muda — ushirikiano uliothibitishwa unakuja hivi karibuni.",

    "about.hospital.backDashboard": "Rudi kwenye dashibodi",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    if (typeof window === "undefined") return "en";
    return localStorage.getItem(LANGUAGE_KEY) || "en";
  });

  useEffect(() => {
    const normalized = translations[language] ? language : "en";
    document.documentElement.lang = normalized === "sw" ? "sw" : "en";
    localStorage.setItem(LANGUAGE_KEY, normalized);
  }, [language]);

  const value = useMemo(() => {
    function setLanguage(nextLanguage) {
      setLanguageState(translations[nextLanguage] ? nextLanguage : "en");
    }

    function t(key, params = {}) {
      const template = translations[language]?.[key] ?? translations.en[key] ?? key;
      return Object.entries(params).reduce(
        (text, [name, replacement]) => text.replaceAll(`{${name}}`, replacement ?? ""),
        template
      );
    }

    return { language, setLanguage, t, languages: LANGUAGES };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}